spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zisharch
    username: zisharch
    password: hazedenard
    
  h2:
    console:
      enabled: true
debug: true
image:
  local: true